language: ruby
cache: bundler
bundler_args: --without benchmarks tools
script:
  - bundle exec rake spec
after_script:
  - bundle exec codeclimate-test-reporter
rvm:
  - 2.4.2
  - 2.3
  - jruby
env:
  global:
    - COVERAGE='true'
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
